version: 2

sphinx:
  configuration: doc/conf.py

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    post_create_environment:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" PYTHON_VIRTUALENV="${READTHEDOCS_VIRTUALENV_PATH}" make users-guide-requirements
