# Wrappers around buck2/haskell.bzl's rules, adapted to how the packages in
# this repository are written:
#
#   * default-language GHC2021 (plus each package's default-extensions) is
#     passed as compiler flags instead of haskell-buck2's fb-haskell set;
#   * `-hide-all-packages`, so that only the listed `packages`/`deps` are in
#     scope, as under Cabal (GHC itself generates the MIN_VERSION_<pkg> CPP
#     macros for the packages it is given, so no cabal_macros.h is needed);
#   * `cabal_paths_module()` generates the `Paths_<pkg>` module that Cabal
#     would autogenerate.
#
# Every rule here takes `packages` (names of Hackage packages, resolved to the
# `@third-party//haskell` targets generated by buck2/gen-haskell-prebuilt.py)
# and `deps` (buck2 targets built from this repository).

load("//buck2:haskell.bzl", _haskell_binary = "haskell_binary", _haskell_library = "haskell_library", _haskell_test = "haskell_test")

# Flags shared by every component in this repository (cabal.project imports
# project-cabal/ghc-options.config on top of each package's own ghc-options).
COMMON_GHC_FLAGS = [
    "-hide-all-packages",
    # Each package is one `ghc --make` action; let it use all cores. GHC's
    # parallel compile is GC-bound with the default 4MB allocation area: a
    # 64MB one took a clean build of everything from 26s to 20s here.
    "-j",
    "+RTS",
    "-A64m",
    "-RTS",
    "-fno-ignore-asserts",
    "-Wall",
    "-Wcompat",
    "-Wtabs",
    "-Wincomplete-uni-patterns",
    "-Wincomplete-record-updates",
    "-Wnoncanonical-monad-instances",
    "-Wno-unticked-promoted-constructors",
    "-Wredundant-constraints",
    # if impl(ghc >= 9.14) in Cabal.cabal / cabal-install.cabal; the buck2
    # build targets whichever GHC cabal's plan.json names, currently 9.14.
    "-Wno-pattern-namespace-specifier",
    "-Wno-incomplete-record-selectors",
]

# The toolchain in buck2/toolchains/BUCK passes -O unconditionally; dev mode
# is meant to be the fast-rebuild one, so switch optimisation off there. Later
# flags win in GHC, and buck2/haskell.bzl adds -O again after these in opt
# mode.
_BUILD_MODE_FLAGS = select({
    "root//buck2/constraints:opt": [],
    "DEFAULT": ["-O0"],
})

# ---------------------------------------------------------------------------
# Paths_<pkg>
# ---------------------------------------------------------------------------

def cabal_paths_module(name, cabal_file, package, visibility = ["PUBLIC"]):
    """Generate the `Paths_<package>` module from the .cabal file's version.

    Declare it in the BUCK file next to the .cabal file and reference it from
    the library's `srcs` dict under the key "Paths_<package>.hs".
    """
    native.genrule(
        name = name,
        srcs = [cabal_file],
        out = "Paths_" + package.replace("-", "_") + ".hs",
        cmd = "sh $(location //project-buck2:gen-paths-module.sh) $SRCS > $OUT",
        visibility = visibility,
    )

# ---------------------------------------------------------------------------
# Rules
# ---------------------------------------------------------------------------

def cabal_library(name, srcs = [], packages = [], deps = [], compiler_flags = [], **kwargs):
    _haskell_library(
        name = name,
        srcs = srcs,
        packages = packages,
        deps = deps,
        fb_haskell = False,
        compiler_flags = COMMON_GHC_FLAGS + _BUILD_MODE_FLAGS + compiler_flags,
        **kwargs
    )

def cabal_binary(name, srcs = [], packages = [], deps = [], compiler_flags = [], **kwargs):
    _haskell_binary(
        name = name,
        srcs = srcs,
        packages = packages,
        deps = deps,
        fb_haskell = False,
        compiler_flags = COMMON_GHC_FLAGS + _BUILD_MODE_FLAGS + compiler_flags,
        **kwargs
    )

def cabal_test(name, srcs = [], packages = [], deps = [], compiler_flags = [], **kwargs):
    """An exitcode-stdio-1.0 test-suite: `buck2 test :name` runs it, and
    `buck2 run :name-bin` runs the underlying executable."""
    _haskell_test(
        name = name,
        srcs = srcs,
        packages = packages,
        deps = deps,
        fb_haskell = False,
        compiler_flags = COMMON_GHC_FLAGS + _BUILD_MODE_FLAGS + compiler_flags,
        **kwargs
    )

def relocated_srcs(prefix, files, extra = {}):
    """Map sources under `prefix/` (a Cabal hs-source-dir that is not the BUCK
    file's own directory) to the paths their module names imply."""
    srcs = {}
    for f in files:
        if not f.startswith(prefix + "/"):
            fail("{} is not under {}/".format(f, prefix))
        srcs[f[len(prefix) + 1:]] = f
    for path, src in extra.items():
        srcs[path] = src
    return srcs
