#!/bin/sh
# Generate a minimal Paths_<pkg> module (as Cabal would autogenerate) from the
# name and version fields of the .cabal file given as the only argument.
# Used by cabal_paths_module() in project-buck2/cabal.bzl.
set -eu

cabal_file=$1
name=$(sed -n 's/^[Nn]ame:[[:space:]]*//p' "$cabal_file" | head -n 1 | tr -d '\r[:space:]')
version=$(sed -n 's/^[Vv]ersion:[[:space:]]*//p' "$cabal_file" | head -n 1 | tr -d '\r[:space:]')

if [ -z "$name" ] || [ -z "$version" ]; then
    echo "gen-paths-module.sh: could not read name/version from $cabal_file" >&2
    exit 1
fi

module=Paths_$(printf '%s' "$name" | tr - _)
branch=$(printf '%s' "$version" | tr . ,)

cat <<HS
{-# LANGUAGE NoRebindableSyntax #-}
{-# OPTIONS_GHC -Wno-missing-import-lists -Wno-unused-imports #-}
-- @generated by project-buck2/gen-paths-module.sh from $cabal_file
-- Only the version is provided: the buck2 build does not install data files.
module $module (version) where

import Data.Version (Version, makeVersion)
import Prelude

version :: Version
version = makeVersion [$branch]
HS
